In [18]:
def is_sorted(numbers):
    numbers = numbers.split()
    return sorted(numbers)

numbers = str(input('Enter Numbers: '))

try:
    for number in numbers.split():
        int(number)
except ValueError:
    raise ValueError('Please enter only numbers')

print('Sorted Numbers:', is_sorted(numbers))

Sorted Numbers: ['1', '2']


# NumPy

#### if you want to manage your array using this library
#### numpy manage multi dimensons array
#### using mathamticle functions
#### using neumaricle computing
#### this is very powerful and speed , manage memory optimization 
#### we can manage multiple data type
#### have a limitation all dimensoans have a size 

In [2]:
%pip install numpy
import numpy as np

my_list = [1, 2, 3, 4, 5]

np.array(my_list)


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


array([1, 2, 3, 4, 5])

In [26]:
zeroz = np.zeros((3, 3))
print(zeroz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
onece = np.ones((2, 4))
print(onece)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
arrange = np.arange(10)
print(arrange)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
random = np.random.rand(3, 3)
print(random)

[[0.37976206 0.56411945 0.57030299]
 [0.02925809 0.60076009 0.35031366]
 [0.93763328 0.22341645 0.52932222]]


# Array Operators

## arithmatic Operators

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum = a + b
print(sum)

diff = a - b
print(diff)

prod = a * b
print(prod)

div = a / b
print(div)

dot = np.dot(a, b)
print(dot)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32


#### 5 is 1 + 4 
#### 7 is 2 + 5
#### 9 is 3 + 6
#### can't using sum multi length arrays

# Metriks Multiplicaton

In [43]:
a = np.array([[0 , 1] , [2 , 3]])
b = np.array([[4 , 5] , [6 , 7]])

dot = np.dot(a, b)
print(dot)

print('Transpose')

a = np.array([[0 , 1] , [2 , 3]])
b = np.array([[4 , 5] , [6 , 7]])

transpose = a.T + b.T

print(transpose)


[[ 6  7]
 [26 31]]
Transpose
[[ 4  8]
 [ 6 10]]


# Array Indexing and Slicing

In [49]:
a = np.array([1 , 2 , 3 , 4 , 5])

print(a[0]) # 0

print(a[1:3]) # 1 to 3

print(a[1:]) # 1 to end

1
[2 3]
[2 3 4 5]


# Array manipulation

In [66]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

reshep_array = array.reshape(2, 5) # 2 rows and 5 columns
print(reshep_array) # [[ 1  2  3  4  5] [ 6  7  8  9 10]]

# concatenate 2 rows
concat = np.concatenate((reshep_array[0], reshep_array[1])) # concatenate 2 rows
print(concat) # [1 2 3 4 5 6 7 8 9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


# Random Number Generation

In [79]:
randomInt = np.random.randint(10 , 101, 5)
print(randomInt)

[78 73 44 46 74]


# Task 1

In [19]:
input_numbers = str(input('Enter Numbers 10 to 50: '))

is_valid = False

try:
    for number in input_numbers.split():
        if int(number) < 10 or int(number) > 50:
            is_valid = False   
        else:
            is_valid = True
        int(number)

except ValueError:
    raise ValueError('Please enter only numbers')

intiger_array = np.array([int(number) for number in input_numbers.split()]) # convert to intiger array

np_array = np.array(intiger_array)

reversed_array = np_array[::-1] # reverse array

if is_valid:
    print('input array:', intiger_array)
    print('reversed_array:', reversed_array)
else:
    print('Please enter numbers between 10 and 50')



input array: [10 20 30 40 50]
reversed_array: [50 40 30 20 10]


# Task 2

In [20]:
array = np.random.randint(1, 100, 12)
reshep_array = array.reshape(3, 4) # 3 rows and 4 columns
print(reshep_array)

[[72 44 46 91]
 [18 42 88 65]
 [60 17 44 97]]


# Task 3

In [23]:
array = np.array([3 , 7 , 9 , 12 , 15])
get_greterthan_10 = array[array > 10]
print(get_greterthan_10)

[12 15]


# Task 4

In [27]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print('Before :',matrix)
broadcast = matrix + 10
print('After',broadcast)

Before : [[1 2 3]
 [4 5 6]]
After [[11 12 13]
 [14 15 16]]


# Pandas

#### we can convert data same pattern
#### data structurs
#### data clean and transformation
#### Data analisis
#### Data visualization
#### Data loading and manipulation

### Key Features:
- Easy data loading from CSV, Excel, and databases.
- Data cleaning and transformation capabilities.
- Support for filtering, grouping, and aggregation.
- Integration with visualization libraries like Matplotlib.


## The Series and Data Structure

In [36]:
%pip install pandas


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


#### Create Data Array

In [38]:
import pandas as pd


data = {
    'name': ['John', 'Doe', 'Anna' , 'Smith' , 'Tom' , 'Mike' , 'Emily'],
    'age': [25, 30, 35 , 40 , 45 , 50 , 55],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio']
}

series = pd.Series(data)
print(series)

name           [John, Doe, Anna, Smith, Tom, Mike, Emily]
age                          [25, 30, 35, 40, 45, 50, 55]
city    [New York, Los Angeles, Chicago, Houston, Phoe...
dtype: object


### Data Frame

In [40]:
import pandas as pd

data = {
    'name': ['John', 'Doe', 'Anna' , 'Smith' , 'Tom' , 'Mike' , 'Emily'],
    'age': [25, 30, 35 , 40 , 45 , 50 , 55],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio'],
    'gender': ['M', 'M', 'F', 'M', 'M', 'M', 'F']   
}

df = pd.DataFrame(data)
print(df)

    name  age          city gender
0   John   25      New York      M
1    Doe   30   Los Angeles      M
2   Anna   35       Chicago      F
3  Smith   40       Houston      M
4    Tom   45       Phoenix      M
5   Mike   50  Philadelphia      M
6  Emily   55   San Antonio      F


# Data Loading and Handling

### Reading Data

## Pandas Library Overview

`pandas` is a powerful Python library for data manipulation and analysis. It provides data structures like `DataFrame` and `Series` to efficiently handle structured data.

### Key Features:
- Easy data loading from CSV, Excel, and databases.
- Data cleaning and transformation capabilities.
- Support for filtering, grouping, and aggregation.
- Integration with visualization libraries like Matplotlib.

### Installation:
```python
!pip install pandas
```

### Basic Usage:
```python
import pandas as pd

data = {"Name": ["Alice", "Bob"], "Age": [25, 30]}
df = pd.DataFrame(data)
print(df)
```

### Generating a CSV File:
```python
df.to_csv("data.csv", index=False)
```

### Reading a CSV File:
```python
df = pd.read_csv("data.csv")
print(df)
```


In [57]:
data = {
    'name': ['John', 'Doe', 'Anna', 'Smith', 'Tom', 'Mike', 'Emily', 'Jake', 'Sophia', 'David', 'Emma', 'Chris', 'Olivia', 'Ryan', 'Ava', 'James', 'Isabella', 'Ethan', 'Mia', 'Liam', 'Charlotte', 'Mason', 'Amelia', 'Lucas', 'Harper', 'Benjamin', 'Evelyn'],
    'age': [25, 30, 35, 40, 45, 50, 55, 22, 29, 33, 38, 42, 47, 52, 57, 26, 31, 36, 41, 46, 51, 56, 27, 32, 37, 43, 48],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte', 'Indianapolis', 'San Francisco', 'Seattle', 'Denver', 'Washington', 'Boston', 'El Paso', 'Detroit', 'Nashville', 'Memphis', 'Portland', 'Oklahoma City'],
    'gender': ['M', 'M', 'F', 'M', 'M', 'M', 'F', 'M', 'F', 'MALE', 'FEMALE', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'F', 'M'],
    'occupation': ['Engineer', 'Doctor', 'Teacher', 'Lawyer', 'Nurse', 'Developer', 'Artist', 'Chef', 'Scientist', 'Writer', 'Designer', 'Musician', 'Pharmacist', 'Accountant', 'Pilot', 'Dentist', 'Journalist', 'Architect', 'Athlete', 'Politician', 'Actor', 'Firefighter', 'Police Officer', 'Paramedic', 'Therapist', 'Surgeon', 'Economist'],
    'salary': [70000, 120000, 55000, 95000, 60000, 110000, 50000, 80000, 90000, 75000, 65000, 72000, 68000, 78000, 85000, 70000, 74000, 98000, 56000, 102000, 89000, 93000, 58000, 77000, 69000, 125000, 96000]
}
df = pd.DataFrame(data)

df.to_csv("data.csv", index=False)

In [60]:
import pandas as pd

df = pd.read_csv("data.csv")
print(df.head()) # print first 5 rows

    name  age         city gender occupation  salary
0   John   25     New York      M   Engineer   70000
1    Doe   30  Los Angeles      M     Doctor  120000
2   Anna   35      Chicago      F    Teacher   55000
3  Smith   40      Houston      M     Lawyer   95000
4    Tom   45      Phoenix      M      Nurse   60000
