In [18]:
def is_sorted(numbers):
    numbers = numbers.split()
    return sorted(numbers)

numbers = str(input('Enter Numbers: '))

try:
    for number in numbers.split():
        int(number)
except ValueError:
    raise ValueError('Please enter only numbers')

print('Sorted Numbers:', is_sorted(numbers))

Sorted Numbers: ['1', '2']


# NumPy

#### if you want to manage your array using this library
#### numpy manage multi dimensons array
#### using mathamticle functions
#### using neumaricle computing
#### this is very powerful and speed , manage memory optimization 
#### we can manage multiple data type
#### have a limitation all dimensoans have a size 

In [25]:
# %pip install numpy
import numpy as np

my_list = [1, 2, 3, 4, 5]

np.array(my_list)

array([1, 2, 3, 4, 5])

In [26]:
zeroz = np.zeros((3, 3))
print(zeroz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
onece = np.ones((2, 4))
print(onece)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
arrange = np.arange(10)
print(arrange)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
random = np.random.rand(3, 3)
print(random)

[[0.37976206 0.56411945 0.57030299]
 [0.02925809 0.60076009 0.35031366]
 [0.93763328 0.22341645 0.52932222]]


# Array Operators

## arithmatic Operators

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum = a + b
print(sum)

diff = a - b
print(diff)

prod = a * b
print(prod)

div = a / b
print(div)

dot = np.dot(a, b)
print(dot)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32


#### 5 is 1 + 4 
#### 7 is 2 + 5
#### 9 is 3 + 6
#### can't using sum multi length arrays

# Metriks Multiplicaton

In [43]:
a = np.array([[0 , 1] , [2 , 3]])
b = np.array([[4 , 5] , [6 , 7]])

dot = np.dot(a, b)
print(dot)

print('Transpose')

a = np.array([[0 , 1] , [2 , 3]])
b = np.array([[4 , 5] , [6 , 7]])

transpose = a.T + b.T

print(transpose)


[[ 6  7]
 [26 31]]
Transpose
[[ 4  8]
 [ 6 10]]
